# Generated by Django 5.1.6 on 2025-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Cibo', 'Cibo'), ('Trasporti', 'Trasporti'), ('Intrattenimento', 'Intrattenimento'), ('Bollette', 'Bollette'), ('Altro', 'Altro')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
